# Generated by Django 2.0.6 on 2018-07-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_site_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
    ]
