# Generated by Django 2.0.6 on 2018-07-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20180713_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='extension',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosimetrist',
            name='extension',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='address1',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='address2',
            field=models.CharField(default='asdF', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='first_five',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
