# Generated by Django 2.0.6 on 2018-07-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20180713_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='initials',
            field=models.CharField(default='XX', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosimetrist',
            name='initials',
            field=models.CharField(default='xx', max_length=3),
            preserve_default=False,
        ),
    ]
