# Generated by Django 2.0.6 on 2018-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.IntegerField()),
                ('date', models.DateField()),
                ('vert', models.DecimalField(decimal_places=1, max_digits=4)),
                ('long', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lat', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
